# DA lab 6주차 연관규칙분석: mlxtend 라이브러리의 활용

## Association Rule Mining

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

### Contents
* TransactionEncoder 함수
* One-hot Array 변환
* Apriori 알고리즘 구현
* 빈발집합 도출
* 연관규칙 분석

### Used Library
* mlxtend
* pandas

### 예제 데이터셋

In [2]:
dataset=[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

### TransactionEncoder 함수: 트랜잭션 데이터를 one-hot array로 바꿔줌

In [3]:
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)

### Boolean 타입으로 encode된 one-hot array

In [4]:
te_ary

array([[False, False, False,  True, False,  True,  True,  True,  True,
        False,  True],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False,  True,  True,  True, False, False,  True,
        False, False]], dtype=bool)

### Int타입으로 encode된 one-hot array

In [5]:
te_ary.astype("int")

array([[0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

### one-hot array의 칼럼은 트랜잭션의 아이템들

In [6]:
te.columns_

['Apple',
 'Corn',
 'Dill',
 'Eggs',
 'Ice cream',
 'Kidney Beans',
 'Milk',
 'Nutmeg',
 'Onion',
 'Unicorn',
 'Yogurt']

### 아이템 목록

In [7]:
te.columns_mapping_

{'Apple': 0,
 'Corn': 1,
 'Dill': 2,
 'Eggs': 3,
 'Ice cream': 4,
 'Kidney Beans': 5,
 'Milk': 6,
 'Nutmeg': 7,
 'Onion': 8,
 'Unicorn': 9,
 'Yogurt': 10}

In [8]:
df=pd.DataFrame(te_ary, columns=te.columns_)

In [9]:
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

### Apriori 알고리즘 실행하기

In [10]:
from mlxtend.frequent_patterns import apriori

In [11]:
apriori(df, min_support=0.6)

    support   itemsets
0       0.8        (3)
1       1.0        (5)
2       0.6        (6)
3       0.6        (8)
4       0.6       (10)
5       0.8     (3, 5)
6       0.6     (8, 3)
7       0.6     (5, 6)
8       0.6     (8, 5)
9       0.6    (10, 5)
10      0.6  (8, 3, 5)

In [12]:
apriori(df, min_support=0.2)

     support             itemsets
0        0.2                  (0)
1        0.4                  (1)
2        0.2                  (2)
3        0.8                  (3)
4        0.2                  (4)
5        1.0                  (5)
6        0.6                  (6)
7        0.4                  (7)
8        0.6                  (8)
9        0.2                  (9)
10       0.6                 (10)
11       0.2               (0, 3)
12       0.2               (0, 5)
13       0.2               (0, 6)
14       0.2               (1, 3)
15       0.2               (1, 4)
16       0.4               (1, 5)
17       0.2               (1, 6)
18       0.2               (8, 1)
19       0.2               (1, 9)
20       0.2              (1, 10)
21       0.2               (2, 3)
22       0.2               (2, 5)
23       0.2               (2, 7)
24       0.2               (8, 2)
25       0.2              (2, 10)
26       0.2               (3, 4)
27       0.8               (3, 5)
28       0.4               (3, 6)
29       0.4               (3, 7)
..       ...                  ...
119      0.2         (8, 3, 5, 6)
120      0.2        (10, 3, 5, 6)
121      0.4         (8, 3, 5, 7)
122      0.4        (10, 3, 5, 7)
123      0.4        (8, 10, 3, 5)
124      0.2         (8, 3, 6, 7)
125      0.2        (10, 3, 6, 7)
126      0.2        (8, 10, 3, 6)
127      0.4        (8, 10, 3, 7)
128      0.2         (8, 5, 6, 7)
129      0.2        (10, 5, 6, 7)
130      0.2        (8, 10, 5, 6)
131      0.2        (9, 10, 5, 6)
132      0.4        (8, 10, 5, 7)
133      0.2        (8, 10, 6, 7)
134      0.2      (8, 1, 3, 4, 5)
135      0.2     (1, 10, 5, 6, 9)
136      0.2      (8, 2, 3, 5, 7)
137      0.2     (10, 2, 3, 5, 7)
138      0.2     (8, 10, 2, 3, 5)
139      0.2     (8, 10, 2, 3, 7)
140      0.2     (8, 2, 10, 5, 7)
141      0.2      (8, 3, 5, 6, 7)
142      0.2     (10, 3, 5, 6, 7)
143      0.2     (8, 10, 3, 5, 6)
144      0.4     (8, 10, 3, 5, 7)
145      0.2     (8, 10, 3, 6, 7)
146      0.2     (8, 10, 5, 6, 7)
147      0.2  (2, 3, 5, 7, 8, 10)
148      0.2  (3, 5, 6, 7, 8, 10)

[149 rows x 2 columns]

### 아이템 셋(아이템 이름 명시)

In [13]:
apriori(df, min_support=0.6, use_colnames=True)

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Kidney Beans, Eggs)
6       0.6                (Eggs, Onion)
7       0.6         (Milk, Kidney Beans)
8       0.6        (Kidney Beans, Onion)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Kidney Beans, Eggs, Onion)

### 빈발집합의 길이

In [14]:
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

In [15]:
frequent_itemsets

    support                                     itemsets  length
0       0.4                                       (Corn)       1
1       0.8                                       (Eggs)       1
2       1.0                               (Kidney Beans)       1
3       0.6                                       (Milk)       1
4       0.4                                     (Nutmeg)       1
5       0.6                                      (Onion)       1
6       0.6                                     (Yogurt)       1
7       0.4                         (Corn, Kidney Beans)       2
8       0.8                         (Kidney Beans, Eggs)       2
9       0.4                                 (Milk, Eggs)       2
10      0.4                               (Nutmeg, Eggs)       2
11      0.6                                (Eggs, Onion)       2
12      0.4                               (Eggs, Yogurt)       2
13      0.6                         (Milk, Kidney Beans)       2
14      0.4                       (Nutmeg, Kidney Beans)       2
15      0.6                        (Kidney Beans, Onion)       2
16      0.6                       (Kidney Beans, Yogurt)       2
17      0.4                               (Milk, Yogurt)       2
18      0.4                              (Nutmeg, Onion)       2
19      0.4                             (Nutmeg, Yogurt)       2
20      0.4                              (Yogurt, Onion)       2
21      0.4                   (Milk, Kidney Beans, Eggs)       3
22      0.4                 (Nutmeg, Kidney Beans, Eggs)       3
23      0.6                  (Kidney Beans, Eggs, Onion)       3
24      0.4                 (Kidney Beans, Eggs, Yogurt)       3
25      0.4                        (Nutmeg, Eggs, Onion)       3
26      0.4                       (Nutmeg, Eggs, Yogurt)       3
27      0.4                        (Eggs, Yogurt, Onion)       3
28      0.4                 (Milk, Kidney Beans, Yogurt)       3
29      0.4                (Nutmeg, Kidney Beans, Onion)       3
30      0.4               (Nutmeg, Kidney Beans, Yogurt)       3
31      0.4                (Kidney Beans, Yogurt, Onion)       3
32      0.4                      (Nutmeg, Yogurt, Onion)       3
33      0.4          (Nutmeg, Kidney Beans, Eggs, Onion)       4
34      0.4         (Nutmeg, Kidney Beans, Eggs, Yogurt)       4
35      0.4          (Kidney Beans, Eggs, Yogurt, Onion)       4
36      0.4                (Nutmeg, Eggs, Yogurt, Onion)       4
37      0.4        (Nutmeg, Kidney Beans, Yogurt, Onion)       4
38      0.4  (Nutmeg, Kidney Beans, Eggs, Yogurt, Onion)       5

### 길이가 2이며, Support 값이 0.8인 빈발집합 찾기

In [16]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.8) ]

   support              itemsets  length
8      0.8  (Kidney Beans, Eggs)       2

### 특정 빈발집합 조회
* 집합내 아이템 순서는 상관없음
* frozenset

In [17]:
frequent_itemsets[ frequent_itemsets['itemsets'] == {'Onion', 'Eggs'} ]

    support       itemsets  length
11      0.6  (Eggs, Onion)       2

### 특정 아이템을 포함한 빈발집합 조회

In [19]:
array=['Onion','Eggs']
frequent_itemsets.loc[frequent_itemsets['itemsets'].isin(array)]

Empty DataFrame
Columns: [support, itemsets, length]
Index: []

### 연관규칙 생성 from 빈발집합

In [63]:
from mlxtend.frequent_patterns import association_rules

### confindence 기준으로 cut-off

In [65]:
rules=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(Yogurt, Kidney Beans)",(Milk),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
1,"(Yogurt, Milk)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
2,"(Milk, Kidney Beans)",(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
3,(Yogurt),"(Milk, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
4,(Kidney Beans),"(Yogurt, Milk)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
5,(Milk),"(Yogurt, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
6,"(Yogurt, Nutmeg)",(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
7,"(Yogurt, Eggs)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf
8,"(Nutmeg, Eggs)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
9,(Yogurt),"(Nutmeg, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
10,(Nutmeg),"(Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
11,(Eggs),"(Yogurt, Nutmeg)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
12,"(Milk, Kidney Beans)",(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
13,"(Milk, Eggs)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
14,"(Kidney Beans, Eggs)",(Milk),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
15,(Milk),"(Kidney Beans, Eggs)",0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
16,(Kidney Beans),"(Milk, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
17,(Eggs),"(Milk, Kidney Beans)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
18,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.000000,1.250000,0.12,inf
19,"(Kidney Beans, Eggs)",(Onion),0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000
20,"(Onion, Eggs)",(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf
21,(Kidney Beans),"(Onion, Eggs)",1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000
22,(Onion),"(Kidney Beans, Eggs)",0.6,0.8,0.6,1.000000,1.250000,0.12,inf
23,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000
24,"(Yogurt, Kidney Beans, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
25,"(Yogurt, Kidney Beans, Onion)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf
26,"(Yogurt, Nutmeg, Onion)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
27,"(Kidney Beans, Nutmeg, Onion)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
28,"(Yogurt, Kidney Beans)","(Nutmeg, Onion)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
29,"(Yogurt, Nutmeg)","(Kidney Beans, Onion)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
...,...,...,...,...,...,...,...,...,...
170,"(Kidney Beans, Eggs)",(Yogurt),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
171,(Yogurt),"(Kidney Beans, Eggs)",0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
172,(Kidney Beans),"(Yogurt, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
173,(Eggs),"(Yogurt, Kidney Beans)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
174,"(Yogurt, Kidney Beans, Onion)",(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
175,"(Yogurt, Kidney Beans, Eggs)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
176,"(Yogurt, Onion, Eggs)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
177,"(Kidney Beans, Onion, Eggs)",(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
178,"(Yogurt, Kidney Beans)","(Onion, Eggs)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
179,"(Yogurt, Onion)","(Kidney Beans, Eggs)",0.4,0.8,0.4,1.000000,1.250000,0.08,inf
180,"(Yogurt, Eggs)","(Kidney Beans, Onion)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
181,"(Kidney Beans, Onion)","(Yogurt, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
182,"(Kidney Beans, Eggs)","(Yogurt, Onion)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
183,"(Onion, Eggs)","(Yogurt, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
184,(Yogurt),"(Kidney Beans, Onion, Eggs)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
185,(Kidney Beans),"(Yogurt, Onion, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
186,(Onion),"(Yogurt, Kidney Beans, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
187,(Eggs),"(Yogurt, Kidney Beans, Onion)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
188,"(Yogurt, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
189,"(Yogurt, Onion)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf
190,"(Nutmeg, Onion)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
191,(Yogurt),"(Nutmeg, Onion)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
192,(Nutmeg),"(Yogurt, Onion)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
193,(Onion),"(Yogurt, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
194,(Yogurt),(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
195,(Eggs),(Yogurt),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
196,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf
197,(Kidney Beans),(Yogurt),1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000
198,(Nutmeg),(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
199,(Onion),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000

### 조건에 맞는 규칙 조회

In [67]:
rules[ (rules['support'] >= 0.8) &
                   (rules['lift'] >= 0.8) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
76,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.8,1.0,0.0,1.000000
77,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.0,1.0,0.0,inf

### 칼럼추가(antecedents 길이)

In [68]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))

In [69]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,"(Yogurt, Kidney Beans)",(Milk),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2
1,"(Yogurt, Milk)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf,2
2,"(Milk, Kidney Beans)",(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2
3,(Yogurt),"(Milk, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
4,(Kidney Beans),"(Yogurt, Milk)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000,1
5,(Milk),"(Yogurt, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
6,"(Yogurt, Nutmeg)",(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf,2
7,"(Yogurt, Eggs)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,2
8,"(Nutmeg, Eggs)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,2
9,(Yogurt),"(Nutmeg, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,1
10,(Nutmeg),"(Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1
11,(Eggs),"(Yogurt, Nutmeg)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,1
12,"(Milk, Kidney Beans)",(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,2
13,"(Milk, Eggs)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf,2
14,"(Kidney Beans, Eggs)",(Milk),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,2
15,(Milk),"(Kidney Beans, Eggs)",0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
16,(Kidney Beans),"(Milk, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000,1
17,(Eggs),"(Milk, Kidney Beans)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
18,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.000000,1.250000,0.12,inf,2
19,"(Kidney Beans, Eggs)",(Onion),0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000,2
20,"(Onion, Eggs)",(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf,2
21,(Kidney Beans),"(Onion, Eggs)",1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000,1
22,(Onion),"(Kidney Beans, Eggs)",0.6,0.8,0.6,1.000000,1.250000,0.12,inf,1
23,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000,1
24,"(Yogurt, Kidney Beans, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,3
25,"(Yogurt, Kidney Beans, Onion)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,3
26,"(Yogurt, Nutmeg, Onion)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf,3
27,"(Kidney Beans, Nutmeg, Onion)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,3
28,"(Yogurt, Kidney Beans)","(Nutmeg, Onion)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,2
29,"(Yogurt, Nutmeg)","(Kidney Beans, Onion)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf,2
...,...,...,...,...,...,...,...,...,...,...
170,"(Kidney Beans, Eggs)",(Yogurt),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,2
171,(Yogurt),"(Kidney Beans, Eggs)",0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
172,(Kidney Beans),"(Yogurt, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000,1
173,(Eggs),"(Yogurt, Kidney Beans)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
174,"(Yogurt, Kidney Beans, Onion)",(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf,3
175,"(Yogurt, Kidney Beans, Eggs)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,3
176,"(Yogurt, Onion, Eggs)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf,3
177,"(Kidney Beans, Onion, Eggs)",(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,3
178,"(Yogurt, Kidney Beans)","(Onion, Eggs)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2
179,"(Yogurt, Onion)","(Kidney Beans, Eggs)",0.4,0.8,0.4,1.000000,1.250000,0.08,inf,2
180,"(Yogurt, Eggs)","(Kidney Beans, Onion)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf,2
181,"(Kidney Beans, Onion)","(Yogurt, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,2
182,"(Kidney Beans, Eggs)","(Yogurt, Onion)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,2
183,"(Onion, Eggs)","(Yogurt, Kidney Beans)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2
184,(Yogurt),"(Kidney Beans, Onion, Eggs)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
185,(Kidney Beans),"(Yogurt, Onion, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000,1
186,(Onion),"(Yogurt, Kidney Beans, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,1
187,(Eggs),"(Yogurt, Kidney Beans, Onion)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,1
188,"(Yogurt, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,2
189,"(Yogurt, Onion)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,2
190,"(Nutmeg, Onion)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,2
191,(Yogurt),"(Nutmeg, Onion)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,1
192,(Nutmeg),"(Yogurt, Onion)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1
193,(Onion),"(Yogurt, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,1
194,(Yogurt),(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
195,(Eggs),(Yogurt),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
196,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf,1
197,(Kidney Beans),(Yogurt),1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000,1
198,(Nutmeg),(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,1
199,(Onion),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,1